// FETCH SEARCH DATA CONSTANT
export const FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA";
export const FETCH_SEARCH_SUCCESS = "FETCH_SEARCH_SUCCESS";
export const FETCH_SEARCH_FAILURE = "FETCH_SEARCH_FAILURE";

// FETCH CURRENT WEATHER CONSTANT
export const FETCH_CURRENT_WEATHER_PENDING = "FETCH_CURRENT_WEATHER_PENDING";
export const FETCH_CURRENT_WEATHER_SUCCESS = "FETCH_CURRENT_WEATHER_SUCCESS";
export const FETCH_CURRENT_WEATHER_ERROR = "FETCH_CURRENT_WEATHER_ERROR";

// SAVED CITIES CONSTANT
export const ADD_CITY = "ADD_CITY";
export const REMOVE_CITY = "REMOVE_CITY";
